apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
spec:
  project: observability
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: k8s-monitoring
      targetRevision: 4.1.6
      helm:
        valueFiles:
          - $values/k8s-monitoring/preprod/values.yaml
    - repoURL: 'https://github.com/dyingstar-game/kubernetes.git'
      targetRevision: main
      ref: values
    - repoURL: 'https://github.com/dyingstar-game/kubernetes.git'
      targetRevision: main
      path: k8s-monitoring/preprod/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k8s-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true