# Harbor image overrides for local dev (skip local build)
# Applied on top of values-dev-local.yaml when using ./scripts_linux/dev.sh with harbor mode

image:
  repository: harbor.dyingstar-game.space/dyingstar/horizon
  pullPolicy: IfNotPresent
  tag: "develop"

pluginsImage:
  repository: harbor.dyingstar-game.space/dyingstar/horizon-plugins
  pullPolicy: IfNotPresent
  tag: "develop"

dataImage:
  enabled: true
  repository: harbor.dyingstar-game.space/dyingstar/horizon-data
  pullPolicy: IfNotPresent
  tag: "develop"
