replicaCount: 1

image:
  repository: harbor.dyingstar-game.space/dyingstar/horizon
  pullPolicy: Always
  tag: "develop"

# uncomment if you use godotserver running in local (F5), otherwise horizon will
#   connect to godotserver pod in minikube
extraEnv:
  # - name: GAME_SERVER_HOST
  #   value: "host.minikube.internal"
  - name: BYPASS_AUTH
    value: "true"
  - name: LIVEKIT_URL
    value: "ws://vocal.dyingstar.local"
  - name: LIVEKIT_API_URL
    value: "http://livekit:7880"
  - name: LIVEKIT_API_KEY
    valueFrom:
      secretKeyRef:
        name: livekit-keys
        key: LIVEKIT_API_KEY
  - name: LIVEKIT_API_SECRET
    valueFrom:
      secretKeyRef:
        name: livekit-keys
        key: LIVEKIT_API_SECRET

service:
  type: ClusterIP
  externalTrafficPolicy: ""

pluginsImage:
  enabled: true
  repository: harbor.dyingstar-game.space/dyingstar/horizon-plugins
  pullPolicy: IfNotPresent
  tag: "develop"


httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
    - name: traefik-gateway 
      namespace: traefik    
      sectionName: web      
  hostnames:
    - "horizon.dyingstar.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
resources:
  requests:
    cpu: 1
    memory: 512Mi
  limits:
    cpu: 4
    memory: 2Gi