apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://grafana-community.github.io/helm-charts'
      chart: grafana
      targetRevision: 12.4.8
      helm:
        valueFiles:
          - $values/grafana/values-dev.yaml
    - repoURL: 'file:///mnt/local-repo.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true