apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: textchat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'file:///mnt/local-repo.git'
    path: textchat
    targetRevision: HEAD
    helm:
      valueFiles:
        - $values/textchat/values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dyingstar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true