deployment:
  replicas: 2

ingressRoute:
  dashboard:
    enabled: false

ports:
  web:
    port: 80
    exposedPort: 80
    nodePort: 30080
    protocol: TCP
    transport:
      respondingTimeouts:
        idleTimeout: 3600s
  websecure:
    port: 443
    exposedPort: 443
    nodePort: 30443
    protocol: TCP
    transport:
      respondingTimeouts:
        idleTimeout: 3600s

service:
  enabled: true
  spec:
    type: NodePort
    externalTrafficPolicy: Local
logs:
  general:
    level: INFO
  access:
    enabled: true

providers:
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true 
  name: traefik-gateway 
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  listeners:
    web:
      port: 80
      protocol: HTTP
      hostname: "*.dyingstar-game.space"
      namespacePolicy:
        from: All
    argocd:
      port: 443
      protocol: HTTPS
      hostname: "argocd.dyingstar-game.space"
      namespacePolicy:
        from: All
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: argocd-tls
    # harbor:
    #   port: 443
    #   protocol: HTTPS
    #   hostname: "harbor.dyingstar-game.space"
    #   namespacePolicy:
    #     from: All
    #   mode: Terminate
    #   certificateRefs:
    #     - kind: Secret
    #       name: harbor-tls