apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: godotserver
  namespace: argocd
spec:
  project: game
  source:
    repoURL: 'file:///mnt/local-repo.git'
    path: godotserver
    targetRevision: HEAD
    helm:
      valueFiles:
        - $values/godotserver/values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dyingstar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true