apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manger
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: 'https://charts.jetstack.io'
      chart: cert-manager
      targetRevision: v1.21.0
      helm:
        valueFiles:
          - $values/cert-manager/values-preprod.yaml
    - repoURL: 'https://github.com/dyingstar-game/kubernetes.git'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m