apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: 'https://github.com/keycloak/keycloak-k8s-resources.git'
      targetRevision: 26.7.0
      path: kubernetes
    - repoURL: 'https://github.com/dyingstar-game/kubernetes.git'
      targetRevision: main
      path: keycloak-managed/preprod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
