apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: infra apps
  
  sourceRepos:
    - 'file:///mnt/local-repo.git'

  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'