# Preprod overrides for service-monitoring.
image:
  repository: harbor.dyingstar-game.space/dyingstar/monitoring
  pullPolicy: Always
  tag: "develop"

serviceMonitor:
  enabled: true

podAnnotations: 
  k8s.grafana.com/scrape: "true"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
