apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: game
  sources:
    - repoURL: 'https://github.com/dyingstar-game/kubernetes.git'
      targetRevision: refacto-and-kube-best-practice
      path: keycloak/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dyingstar-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
