apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-persistence
  namespace: argocd
spec:
  project: game
  source:
    repoURL: 'https://github.com/dyingstar-game/kubernetes.git'
    path: service-persistence
    targetRevision: refacto-and-kube-best-practice
    helm:
      valueFiles:
        - $values/service-persistence/values-preprod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dyingstar-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true