apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-persistence.fullname" . }}
  labels:
    {{- include "service-persistence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service-persistence.selectorLabels" . | nindent 4 }}
