apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: horizon
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dyingstar-game/kubernetes.git'
    path: horizon
    targetRevision: refacto-and-kube-best-practice
    helm:
      valueFiles:
        - $values/horizon/values-preprod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dyingstar-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true