apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: textchat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dyingstar-game/kubernetes.git'
    path: textchat
    targetRevision: main
    helm:
      valueFiles:
        - $values/textchat/values-preprod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dyingstar-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true